# Generated by Django 3.2 on 2023-01-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230117_0929'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrLineItem',
            new_name='OrderLineItem',
        ),
    ]
